import Navbar from "../Navbar/Navbar";

const Tribalism = () => {

    return (
        <div>
            <Navbar/>
            <div className="pt-10 px-20 pb-20">
              <h1 className='text-4xl font-bold dark:text-white mb-3'>Tribalism</h1>
              <p className='mb-6 text-lg font-normal text-gray-500 dark:text-gray-400'>The notion that African societies are “tribal” is one of the most widespread ideas associated with the continent. The word “tribe” is rarely questioned when describing African peoples, nations, or communities. This word, however, carries harmful connotations of primitivity and has historically been used to depict non-Western indigenous societies as simplistic and uncivilized.</p>
              <p className='mb-6 text-lg font-normal text-gray-500 dark:text-gray-400'>First of all, what makes a tribe a tribe? The matter is not as simple as people sharing a common language or culture. In fact, African groups and communities described as tribes have extremely little in common in terms of size, socio-political organization, or way of life. The few hundred El Molo people in Kenya are often described as a tribe, and so are over 43 million Yoruba people. In fact, the term is so ill-defined that academics have been calling for its rejection for decades now. Columbia University Distinguished Professor of Anthropology Morton H. Fried argued in the mid-70s that “the term is so ambiguous and confusing that it should be abandoned by social scientists.”</p>
              <p className='mb-6 text-lg font-normal text-gray-500 dark:text-gray-400'>Since the category lacks rigorous definition, it is worth it for us to interrogate how it gets applied.  Are the Catalans a tribe? How about the Bretons? European groups are often described as nations, peoples, minority groups, or even ethnic groups, but never tribes. This discrepancy shouldn’t come as a surprise. Indeed, the contemporary uses of the term were developed during the 19th-century, where pseudo-scientific theories characterized non-Western societies in Africa, Asia, and the Americas as inferior and less evolved, in order to justify colonial expansion in the name of civilizing missions. In fact, colonial power not only exploited the idea of tribal societies, they often created and imposed those structures.</p>
              <p className='mb-6 text-lg italic font-normal text-gray-500 dark:text-gray-400'>“Calling nearly all African social groups tribes and African identities tribal in the era of scientific racism turned the idea of tribe from a social science category into a racial stereotype. By definition, Africans were supposed to live in tribes, preferably with chiefs. The colonizers proposed to govern cheaply by adapting tribal and chiefship institutions into European-style bureaucratic states. If they didn’t find tribes and chiefs, they encouraged people to identify as tribes, and appointed chiefs. In some places, like Rwanda or Nigeria, colonial racial theory led to favoring one ethnic group over another because of supposed racial superiority (meaning white ancestry). In other places, emphasis on tribes was simply a tool of divide and rule strategies. The idea of tribe we have today cannot escape these roots.” <a href="https://kora.matrix.msu.edu/files/50/304/32-130-153D-84-Background_Paper_010_opt.pdf">Chris Lowe, Talking About “Tribe”</a></p>
              <p className='mb-6 text-lg italic font-normal text-gray-500 dark:text-gray-400'>Unfortunately, we still have a long way to go to undo this legacy. Swapping out the problematic language of “tribes” with alternatives like “ethnic group” doesn’t cut it either (as a side note, please never use the blanket adjective “ethnic” to describe individuals, names, food, or fashion: You really just mean non-Western). Instead, it is our whole framing of Africa’s societies and current events which we must recontextualize.</p>
              <p className='mb-6 text-lg italic font-normal text-gray-500 dark:text-gray-400'>For instance, whenever there is socio-political unrest in Africa, no matter how different the circumstances are, it is often explained away as tribal or ethnic conflict. Whether it is the Biafran war, the <a href="https://www.nytimes.com/1994/06/12/weekinreview/june-5-10-new-atrocities-africa-three-bishops-10-priests-are-slaughtered-rwanda.html">Rwandan genocide</a>, the <a href="https://www.nytimes.com/2007/12/30/world/africa/30cnd-kenya.html">2007 Kenyan electoral crisis</a>, or the <a href="https://www.cnn.com/2016/11/21/africa/libya-monkey-tribes-deadly-clash-trnd/index.html">Libyan civil war</a>, the media is quick to point out the main cause: tribalism and ethnic enmities. Yet, the idea that ethnic skirmishes are the main catalyst for any of these events has been <a href="https://origins.osu.edu/article/beyond-tribes-violence-and-politics-kenya">challenged</a>, <a href="https://www.jstor.org/stable/4029016?seq=1#page_scan_tab_contents">criticized</a>, and <a href="https://www.cetri.be/Libya-s-revolution-tribe-nation?lang=fr">thoroughly debunked</a>. At best, it is an oversimplification which obfuscates the socio-economic, political, and historical factors at play. At its worst, it is sheer intellectual laziness, which substitutes specific analysis for prevailing stereotypes, and entrenches the notion that complex African conflicts are nothing more than age-old “tribal rivalries.” It can promote ineffectual solutions and justify complete inaction in the face of legitimate humanitarian crises.</p>
          </div>
      </div>
    );
  }
  
  export default Tribalism